apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.name" . }}
  namespace: kube-system

spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 8000
      targetPort: 8000
      nodePort: 30080
    - protocol: TCP
      name: admin
      targetPort: 8080
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443
      targetPort: 4443
      nodePort: 30443
  selector:
    app: {{ template "traefik.name" . }}